// In this file you can specify the trial data for your experiment


const practice_trials = {
    keyPress: {
    practice: [
        {
            picture: "images/practice/13_50_same.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/practice/13_50_different.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/practice/13_150_same.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/practice/13_150_different.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "different",
            angle: 150,
        },
        {
            picture: "images/practice/14_50_same.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/practice/14_50_different.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/practice/14_150_same.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/practice/14_150_different.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "different",
            angle: 150,
        },
        {
            picture: "images/practice/15_50_same.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/practice/15_50_different.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/practice/15_150_same.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/practice/15_150_different.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "different",
            angle: 150,
        }
        ]
    }
};

const main_trials = {
    keyPress: {
        main: [
        {
            picture: "images/main/1_50_different.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/main/1_50_same.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/main/1_150_different.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "different",
            angle: 150,
        },
        {
            picture: "images/main/1_150_same.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/main/2_50_different.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/main/2_50_same.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/main/2_150_different.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "different",
            angle: 150,
        },
        {
            picture: "images/main/2_150_same.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/main/3_50_different.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/main/3_50_same.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/main/3_150_different.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "different",
            angle: 150,
        },
        {
            picture: "images/main/3_150_same.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/main/4_50_different.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/main/4_50_same.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/main/4_150_different.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "different",
            angle: 150,
        },
        {
            picture: "images/main/4_150_same.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/main/5_50_different.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/main/5_50_same.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/main/5_150_different.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "different",
            angle: 150,
        },
        {
            picture: "images/main/5_150_same.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/main/6_50_different.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/main/6_50_same.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/main/6_150_different.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "different",
            angle: 150,
        },
        {
            picture: "images/main/6_150_same.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/main/7_50_different.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/main/7_50_same.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/main/7_150_different.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "different",
            angle: 150,
        },
        {
            picture: "images/main/7_150_same.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/main/8_50_different.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/main/8_50_same.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/main/8_150_different.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "different",
            angle: 150,
        },
        {
            picture: "images/main/8_150_same.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/main/9_50_different.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/main/9_50_same.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/main/9_150_different.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "different",
            angle: 150,
        },
        {
            picture: "images/main/9_150_same.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/main/10_50_different.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/main/10_50_same.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/main/10_150_different.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "different",
            angle: 150,
        },
        {
            picture: "images/main/10_150_same.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/main/11_50_different.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/main/11_50_same.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/main/11_150_different.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "different",
            angle: 150,
        },
        {
            picture: "images/main/11_150_same.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/main/12_50_different.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/main/12_50_same.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/main/12_150_different.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "different",
            angle: 150,
        },
        {
            picture: "images/main/12_150_same.jpg",
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
            expected: "same",
            angle: 150,
        }
        ]
    }
}
